
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
<<<<<<< HEAD
          pip install -r requirements.txt  
=======
>>>>>>> 2ae5934fad208ce43befa864031eca3c5fe229a2

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py'
